# Generated by Django 3.1.3 on 2020-11-15 22:51

from django.db import migrations


def data_forward(Animal):
    for animal in Animal.objects.all():
        animal.name += " ZZ"
        animal.save()


def forward(apps, schema_editor):
    Animal = apps.get_model("app_a", "Animal")
    data_forward(Animal)


class Migration(migrations.Migration):

    dependencies = [
        ('app_a', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forward, migrations.RunPython.noop),
    ]
