name: Pull Request Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  run_tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main

    - uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - uses: abatilo/actions-poetry@v2.0.0
      with:
        poetry-version: 1.1.2

    - name: Run Tests
      run: |
        python -m venv venv && \
          source venv/bin/activate && \
          poetry install && \
          make test